import type { VariableCategory } from "./types";

/**
 * A curated knowledge base of real SaaS/dev-tool companies and the env var
 * name fragments their SDKs/docs conventionally use. This drives both
 * variable classification (`classifyVariable`) and provider identification
 * (`findProvider`) without any ML/LLM involved — it's a static lookup table,
 * same spirit as the original hand-written RULES list, just at the scale a
 * real multi-tenant scanning product needs (hundreds of vendors, not ten).
 *
 * `keywords` are matched as case-insensitive substrings against the env var
 * name. Longer/more specific keywords are preferred when several providers
 * match the same key (see `findProvider`), so listing a distinctive brand
 * token (e.g. "SENDGRID") is safer than a generic word.
 */
export interface Provider {
  name: string;
  category: VariableCategory;
  keywords: string[];
}

// Canonical credential/config suffixes a provider's env vars typically use,
// grouped by category. Combined with each provider's primary keyword these
// generate the recognized "known env key" surface (~5000 entries across all
// providers) used for coverage stats and docs — see `KNOWN_ENV_KEYS` below.
const CATEGORY_SUFFIXES: Record<VariableCategory, string[]> = {
  database: [
    "URL",
    "CONNECTION_STRING",
    "HOST",
    "PORT",
    "USER",
    "USERNAME",
    "PASSWORD",
    "NAME",
    "DATABASE",
    "SSL_MODE",
  ],
  cache: ["URL", "HOST", "PORT", "PASSWORD", "TOKEN", "TLS_URL", "REST_URL", "REST_TOKEN"],
  storage: [
    "ACCESS_KEY_ID",
    "SECRET_ACCESS_KEY",
    "ACCESS_KEY",
    "SECRET_KEY",
    "BUCKET",
    "BUCKET_NAME",
    "REGION",
    "ENDPOINT",
    "CDN_URL",
  ],
  auth: [
    "CLIENT_ID",
    "CLIENT_SECRET",
    "DOMAIN",
    "ISSUER",
    "SECRET",
    "API_KEY",
    "PUBLISHABLE_KEY",
    "JWT_SECRET",
    "REDIRECT_URI",
  ],
  email: ["API_KEY", "SECRET", "FROM_EMAIL", "USERNAME", "PASSWORD", "SMTP_HOST", "SMTP_PORT", "WEBHOOK_SECRET"],
  sms: ["API_KEY", "AUTH_TOKEN", "ACCOUNT_SID", "SECRET", "FROM_NUMBER", "PHONE_NUMBER"],
  ai: ["API_KEY", "ORG_ID", "PROJECT_ID", "MODEL", "ENDPOINT", "API_VERSION"],
  payments: [
    "SECRET_KEY",
    "PUBLISHABLE_KEY",
    "PUBLIC_KEY",
    "API_KEY",
    "WEBHOOK_SECRET",
    "CLIENT_ID",
    "CLIENT_SECRET",
    "MERCHANT_ID",
  ],
  analytics: ["API_KEY", "WRITE_KEY", "PROJECT_ID", "TOKEN", "SITE_ID", "MEASUREMENT_ID"],
  monitoring: ["DSN", "API_KEY", "TOKEN", "PROJECT_ID", "AUTH_TOKEN", "APP_KEY"],
  ci: ["TOKEN", "API_KEY", "DEPLOY_HOOK", "PROJECT_ID", "ORG_ID", "WEBHOOK_SECRET"],
  crm: ["API_KEY", "TOKEN", "CLIENT_ID", "CLIENT_SECRET", "WEBHOOK_SECRET", "ACCESS_TOKEN"],
  search: ["API_KEY", "ADMIN_API_KEY", "APP_ID", "INDEX_NAME", "URL", "SEARCH_KEY"],
  "feature-flags": ["SDK_KEY", "CLIENT_KEY", "API_KEY", "ENVIRONMENT_KEY", "PROJECT_KEY"],
  maps: ["API_KEY", "ACCESS_TOKEN", "APP_ID", "APP_CODE"],
  video: ["API_KEY", "API_SECRET", "TOKEN", "APP_ID", "STREAM_KEY"],
  cms: ["API_KEY", "ACCESS_TOKEN", "SPACE_ID", "PROJECT_ID", "PREVIEW_TOKEN", "DATASET"],
  security: ["TOKEN", "API_KEY", "SITE_KEY", "SECRET_KEY", "CLIENT_TOKEN"],
  blockchain: ["API_KEY", "PROJECT_ID", "RPC_URL", "APP_ID", "PRIVATE_KEY"],
  social: ["API_KEY", "API_SECRET", "CLIENT_ID", "CLIENT_SECRET", "ACCESS_TOKEN", "BEARER_TOKEN"],
  hosting: ["TOKEN", "API_KEY", "PROJECT_ID", "DEPLOY_HOOK", "TEAM_ID"],
  url: ["URL", "ENDPOINT"],
  other: ["API_KEY", "TOKEN", "SECRET"],
};

export const CATEGORY_LABELS: Record<VariableCategory, string> = {
  database: "Database client",
  cache: "Cache / queue",
  storage: "Object storage",
  auth: "Authentication",
  email: "Email/SMTP",
  sms: "SMS / messaging",
  ai: "AI provider",
  payments: "Payments",
  analytics: "Analytics",
  monitoring: "Monitoring & observability",
  ci: "CI/CD & hosting",
  crm: "CRM & support",
  search: "Search",
  "feature-flags": "Feature flags",
  maps: "Maps & geolocation",
  video: "Video & media",
  cms: "Content management",
  security: "Security & secrets",
  blockchain: "Blockchain / web3",
  social: "Social platform",
  hosting: "Hosting & deploys",
  url: "Application URL",
  other: "Application configuration",
};

export const PROVIDERS: Provider[] = [
  // ---- Database / backend-as-a-service (≈45) ----
  { name: "Supabase", category: "database", keywords: ["SUPABASE"] },
  { name: "PlanetScale", category: "database", keywords: ["PLANETSCALE"] },
  { name: "MongoDB", category: "database", keywords: ["MONGODB", "MONGO_"] },
  { name: "MongoDB Atlas", category: "database", keywords: ["ATLAS_URI"] },
  { name: "PostgreSQL", category: "database", keywords: ["POSTGRES", "PG_", "PGHOST", "PGUSER"] },
  { name: "MySQL", category: "database", keywords: ["MYSQL"] },
  { name: "MariaDB", category: "database", keywords: ["MARIADB"] },
  { name: "SQLite", category: "database", keywords: ["SQLITE"] },
  { name: "CockroachDB", category: "database", keywords: ["COCKROACH"] },
  { name: "Neon", category: "database", keywords: ["NEON_DATABASE", "NEON_URL", "NEON_DB"] },
  { name: "Turso", category: "database", keywords: ["TURSO"] },
  { name: "Firebase", category: "database", keywords: ["FIREBASE"] },
  { name: "Firestore", category: "database", keywords: ["FIRESTORE"] },
  { name: "Fauna", category: "database", keywords: ["FAUNA"] },
  { name: "Amazon DynamoDB", category: "database", keywords: ["DYNAMODB", "DYNAMO_TABLE"] },
  { name: "Apache Cassandra", category: "database", keywords: ["CASSANDRA"] },
  { name: "ScyllaDB", category: "database", keywords: ["SCYLLA"] },
  { name: "Couchbase", category: "database", keywords: ["COUCHBASE"] },
  { name: "RethinkDB", category: "database", keywords: ["RETHINKDB"] },
  { name: "ArangoDB", category: "database", keywords: ["ARANGO"] },
  { name: "Xata", category: "database", keywords: ["XATA"] },
  { name: "Convex", category: "database", keywords: ["CONVEX"] },
  { name: "Hasura", category: "database", keywords: ["HASURA"] },
  { name: "EdgeDB", category: "database", keywords: ["EDGEDB"] },
  { name: "TimescaleDB", category: "database", keywords: ["TIMESCALE"] },
  { name: "InfluxDB", category: "database", keywords: ["INFLUXDB"] },
  { name: "Snowflake", category: "database", keywords: ["SNOWFLAKE"] },
  { name: "Google BigQuery", category: "database", keywords: ["BIGQUERY"] },
  { name: "Amazon Redshift", category: "database", keywords: ["REDSHIFT"] },
  { name: "Databricks", category: "database", keywords: ["DATABRICKS"] },
  { name: "ClickHouse", category: "database", keywords: ["CLICKHOUSE"] },
  { name: "Airtable", category: "database", keywords: ["AIRTABLE"] },
  { name: "Directus", category: "database", keywords: ["DIRECTUS"] },
  { name: "Neo4j", category: "database", keywords: ["NEO4J"] },
  { name: "TiDB", category: "database", keywords: ["TIDB"] },
  { name: "YugabyteDB", category: "database", keywords: ["YUGABYTE"] },
  { name: "SurrealDB", category: "database", keywords: ["SURREALDB"] },
  { name: "RavenDB", category: "database", keywords: ["RAVENDB"] },
  { name: "Prisma Data Platform", category: "database", keywords: ["PRISMA_"] },
  { name: "Motherduck", category: "database", keywords: ["MOTHERDUCK"] },
  { name: "Grafbase", category: "database", keywords: ["GRAFBASE"] },
  { name: "Nhost", category: "database", keywords: ["NHOST"] },
  { name: "AppWrite", category: "database", keywords: ["APPWRITE"] },
  { name: "PocketBase", category: "database", keywords: ["POCKETBASE"] },
  { name: "SingleStore", category: "database", keywords: ["SINGLESTORE"] },

  // ---- Cache / queue / pub-sub (≈24) ----
  { name: "Redis", category: "cache", keywords: ["REDIS"] },
  { name: "Upstash", category: "cache", keywords: ["UPSTASH"] },
  { name: "Memcached", category: "cache", keywords: ["MEMCACHED"] },
  { name: "RabbitMQ", category: "cache", keywords: ["RABBITMQ"] },
  { name: "Apache Kafka", category: "cache", keywords: ["KAFKA"] },
  { name: "Amazon SQS", category: "cache", keywords: ["SQS_"] },
  { name: "Amazon SNS", category: "cache", keywords: ["SNS_TOPIC"] },
  { name: "Google Pub/Sub", category: "cache", keywords: ["PUBSUB_"] },
  { name: "Azure Service Bus", category: "cache", keywords: ["SERVICEBUS"] },
  { name: "NATS", category: "cache", keywords: ["NATS_URL"] },
  { name: "Celery", category: "cache", keywords: ["CELERY_"] },
  { name: "BullMQ", category: "cache", keywords: ["BULLMQ"] },
  { name: "Sidekiq", category: "cache", keywords: ["SIDEKIQ"] },
  { name: "Temporal", category: "cache", keywords: ["TEMPORAL_"] },
  { name: "Inngest", category: "cache", keywords: ["INNGEST"] },
  { name: "Trigger.dev", category: "cache", keywords: ["TRIGGER_DEV", "TRIGGER_API_KEY"] },
  { name: "Upstash QStash", category: "cache", keywords: ["QSTASH"] },
  { name: "Redpanda", category: "cache", keywords: ["REDPANDA"] },
  { name: "Apache ActiveMQ", category: "cache", keywords: ["ACTIVEMQ"] },
  { name: "Apache Pulsar", category: "cache", keywords: ["PULSAR_"] },
  { name: "Beanstalkd", category: "cache", keywords: ["BEANSTALKD"] },
  { name: "Resque", category: "cache", keywords: ["RESQUE_"] },
  { name: "Gearman", category: "cache", keywords: ["GEARMAN"] },
  { name: "Faktory", category: "cache", keywords: ["FAKTORY"] },

  // ---- Storage / CDN / media delivery (≈30) ----
  { name: "AWS S3", category: "storage", keywords: ["S3_BUCKET", "AWS_S3", "S3_ACCESS"] },
  { name: "Cloudflare R2", category: "storage", keywords: ["R2_BUCKET", "R2_ACCESS", "CLOUDFLARE_R2"] },
  { name: "Google Cloud Storage", category: "storage", keywords: ["GCS_BUCKET", "GOOGLE_CLOUD_STORAGE"] },
  { name: "Azure Blob Storage", category: "storage", keywords: ["AZURE_STORAGE", "AZURE_BLOB"] },
  { name: "Backblaze B2", category: "storage", keywords: ["B2_BUCKET", "BACKBLAZE"] },
  { name: "DigitalOcean Spaces", category: "storage", keywords: ["SPACES_BUCKET", "DO_SPACES"] },
  { name: "Cloudinary", category: "storage", keywords: ["CLOUDINARY"] },
  { name: "Imgix", category: "storage", keywords: ["IMGIX"] },
  { name: "Uploadcare", category: "storage", keywords: ["UPLOADCARE"] },
  { name: "Bunny CDN", category: "storage", keywords: ["BUNNY_CDN", "BUNNYCDN"] },
  { name: "Fastly", category: "storage", keywords: ["FASTLY"] },
  { name: "Akamai", category: "storage", keywords: ["AKAMAI"] },
  { name: "KeyCDN", category: "storage", keywords: ["KEYCDN"] },
  { name: "Wasabi", category: "storage", keywords: ["WASABI"] },
  { name: "MinIO", category: "storage", keywords: ["MINIO"] },
  { name: "Filestack", category: "storage", keywords: ["FILESTACK"] },
  { name: "Transloadit", category: "storage", keywords: ["TRANSLOADIT"] },
  { name: "ImageKit", category: "storage", keywords: ["IMAGEKIT"] },
  { name: "Vercel Blob", category: "storage", keywords: ["BLOB_READ_WRITE_TOKEN", "VERCEL_BLOB"] },
  { name: "Cloudflare Images", category: "storage", keywords: ["CLOUDFLARE_IMAGES"] },
  { name: "Sirv", category: "storage", keywords: ["SIRV_"] },
  { name: "StackPath", category: "storage", keywords: ["STACKPATH"] },
  { name: "CacheFly", category: "storage", keywords: ["CACHEFLY"] },
  { name: "Contentful Images API", category: "storage", keywords: ["CONTENTFUL_IMAGES"] },
  { name: "ImageEngine", category: "storage", keywords: ["IMAGEENGINE"] },
  { name: "Cloudflare Turnstile CDN", category: "storage", keywords: ["CF_CDN"] },
  { name: "Rackspace Cloud Files", category: "storage", keywords: ["RACKSPACE_"] },
  { name: "Alibaba Cloud OSS", category: "storage", keywords: ["ALIYUN_OSS", "OSS_BUCKET"] },
  { name: "Tencent Cloud COS", category: "storage", keywords: ["TENCENT_COS"] },
  { name: "IBM Cloud Object Storage", category: "storage", keywords: ["IBM_COS"] },

  // ---- Auth / identity (≈35) ----
  { name: "Auth0", category: "auth", keywords: ["AUTH0"] },
  { name: "Clerk", category: "auth", keywords: ["CLERK"] },
  { name: "NextAuth / Auth.js", category: "auth", keywords: ["NEXTAUTH", "AUTHJS"] },
  { name: "Okta", category: "auth", keywords: ["OKTA"] },
  { name: "Firebase Auth", category: "auth", keywords: ["FIREBASE_AUTH"] },
  { name: "AWS Cognito", category: "auth", keywords: ["COGNITO"] },
  { name: "WorkOS", category: "auth", keywords: ["WORKOS"] },
  { name: "SuperTokens", category: "auth", keywords: ["SUPERTOKENS"] },
  { name: "Ory", category: "auth", keywords: ["ORY_"] },
  { name: "FusionAuth", category: "auth", keywords: ["FUSIONAUTH"] },
  { name: "Keycloak", category: "auth", keywords: ["KEYCLOAK"] },
  { name: "OneLogin", category: "auth", keywords: ["ONELOGIN"] },
  { name: "Ping Identity", category: "auth", keywords: ["PINGIDENTITY", "PING_IDENTITY"] },
  { name: "Frontegg", category: "auth", keywords: ["FRONTEGG"] },
  { name: "Stytch", category: "auth", keywords: ["STYTCH"] },
  { name: "Magic (Magic.link)", category: "auth", keywords: ["MAGIC_LINK", "MAGIC_PUBLISHABLE", "MAGIC_SECRET"] },
  { name: "Descope", category: "auth", keywords: ["DESCOPE"] },
  { name: "Kinde", category: "auth", keywords: ["KINDE"] },
  { name: "Logto", category: "auth", keywords: ["LOGTO"] },
  { name: "Userfront", category: "auth", keywords: ["USERFRONT"] },
  { name: "PropelAuth", category: "auth", keywords: ["PROPELAUTH"] },
  { name: "Zitadel", category: "auth", keywords: ["ZITADEL"] },
  { name: "JumpCloud", category: "auth", keywords: ["JUMPCLOUD"] },
  { name: "Duo Security", category: "auth", keywords: ["DUO_SECURITY", "DUO_IKEY", "DUO_SKEY"] },
  { name: "Google Identity", category: "auth", keywords: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"] },
  { name: "Microsoft Entra ID", category: "auth", keywords: ["AZURE_AD", "ENTRA_ID", "MICROSOFT_CLIENT_ID"] },
  { name: "GitHub OAuth", category: "auth", keywords: ["GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET"] },
  { name: "GitLab OAuth", category: "auth", keywords: ["GITLAB_CLIENT_ID", "GITLAB_CLIENT_SECRET"] },
  { name: "Twitter/X OAuth", category: "auth", keywords: ["TWITTER_CLIENT_ID", "TWITTER_CONSUMER"] },
  { name: "Facebook Login", category: "auth", keywords: ["FACEBOOK_APP_ID", "FACEBOOK_APP_SECRET"] },
  { name: "Apple Sign In", category: "auth", keywords: ["APPLE_CLIENT_ID", "APPLE_TEAM_ID", "APPLE_KEY_ID"] },
  { name: "LinkedIn OAuth", category: "auth", keywords: ["LINKEDIN_CLIENT_ID"] },
  { name: "Discord OAuth", category: "auth", keywords: ["DISCORD_CLIENT_ID", "DISCORD_CLIENT_SECRET"] },
  { name: "Passage by 1Password", category: "auth", keywords: ["PASSAGE_APP_ID"] },
  { name: "Warrant", category: "auth", keywords: ["WARRANT_API_KEY"] },

  // ---- Email (≈24) ----
  { name: "SendGrid", category: "email", keywords: ["SENDGRID"] },
  { name: "Mailgun", category: "email", keywords: ["MAILGUN"] },
  { name: "Resend", category: "email", keywords: ["RESEND"] },
  { name: "Postmark", category: "email", keywords: ["POSTMARK"] },
  { name: "Amazon SES", category: "email", keywords: ["SES_", "AWS_SES"] },
  { name: "Mailchimp", category: "email", keywords: ["MAILCHIMP"] },
  { name: "Mailjet", category: "email", keywords: ["MAILJET"] },
  { name: "SparkPost", category: "email", keywords: ["SPARKPOST"] },
  { name: "Brevo (Sendinblue)", category: "email", keywords: ["BREVO", "SENDINBLUE"] },
  { name: "Loops", category: "email", keywords: ["LOOPS_API_KEY"] },
  { name: "Customer.io", category: "email", keywords: ["CUSTOMERIO", "CUSTOMER_IO"] },
  { name: "Mandrill", category: "email", keywords: ["MANDRILL"] },
  { name: "SMTP2GO", category: "email", keywords: ["SMTP2GO"] },
  { name: "Elastic Email", category: "email", keywords: ["ELASTICEMAIL"] },
  { name: "Mailtrap", category: "email", keywords: ["MAILTRAP"] },
  { name: "MailerSend", category: "email", keywords: ["MAILERSEND"] },
  { name: "Zoho Mail", category: "email", keywords: ["ZOHO_MAIL"] },
  { name: "SocketLabs", category: "email", keywords: ["SOCKETLABS"] },
  { name: "Netcore", category: "email", keywords: ["NETCORE_"] },
  { name: "Courier", category: "email", keywords: ["COURIER_API_KEY", "COURIER_AUTH_TOKEN"] },
  { name: "Sender.net", category: "email", keywords: ["SENDER_API_KEY"] },
  { name: "Moosend", category: "email", keywords: ["MOOSEND"] },
  { name: "Generic SMTP", category: "email", keywords: ["SMTP_HOST", "SMTP_USER", "SMTP_PASSWORD", "SMTP_PORT"] },
  { name: "Postal", category: "email", keywords: ["POSTAL_API_KEY"] },

  // ---- SMS / real-time messaging (≈25) ----
  { name: "Twilio", category: "sms", keywords: ["TWILIO"] },
  { name: "Vonage (Nexmo)", category: "sms", keywords: ["VONAGE", "NEXMO"] },
  { name: "MessageBird", category: "sms", keywords: ["MESSAGEBIRD"] },
  { name: "Plivo", category: "sms", keywords: ["PLIVO"] },
  { name: "Sinch", category: "sms", keywords: ["SINCH"] },
  { name: "Bandwidth", category: "sms", keywords: ["BANDWIDTH_"] },
  { name: "Telnyx", category: "sms", keywords: ["TELNYX"] },
  { name: "ClickSend", category: "sms", keywords: ["CLICKSEND"] },
  { name: "Infobip", category: "sms", keywords: ["INFOBIP"] },
  { name: "Kaleyra", category: "sms", keywords: ["KALEYRA"] },
  { name: "TextMagic", category: "sms", keywords: ["TEXTMAGIC"] },
  { name: "EZ Texting", category: "sms", keywords: ["EZTEXTING"] },
  { name: "Slack", category: "sms", keywords: ["SLACK_WEBHOOK", "SLACK_BOT_TOKEN", "SLACK_APP_TOKEN"] },
  { name: "Discord", category: "sms", keywords: ["DISCORD_WEBHOOK", "DISCORD_BOT_TOKEN"] },
  { name: "Microsoft Teams", category: "sms", keywords: ["TEAMS_WEBHOOK"] },
  { name: "Telegram Bot API", category: "sms", keywords: ["TELEGRAM_BOT_TOKEN", "TELEGRAM_API"] },
  { name: "WhatsApp Business API", category: "sms", keywords: ["WHATSAPP_"] },
  { name: "Zendesk Chat", category: "sms", keywords: ["ZENDESK_CHAT"] },
  { name: "Intercom Messenger", category: "sms", keywords: ["INTERCOM_ACCESS_TOKEN"] },
  { name: "Crisp", category: "sms", keywords: ["CRISP_"] },
  { name: "Pusher", category: "sms", keywords: ["PUSHER_"] },
  { name: "Ably", category: "sms", keywords: ["ABLY_"] },
  { name: "PubNub", category: "sms", keywords: ["PUBNUB"] },
  { name: "Novu", category: "sms", keywords: ["NOVU_"] },
  { name: "OneSignal", category: "sms", keywords: ["ONESIGNAL"] },

  // ---- AI / ML (≈30) ----
  { name: "OpenAI", category: "ai", keywords: ["OPENAI"] },
  { name: "Anthropic", category: "ai", keywords: ["ANTHROPIC", "CLAUDE_API"] },
  { name: "Cohere", category: "ai", keywords: ["COHERE"] },
  { name: "Google Gemini", category: "ai", keywords: ["GEMINI_API"] },
  { name: "Google Vertex AI", category: "ai", keywords: ["VERTEX_AI"] },
  { name: "Azure OpenAI", category: "ai", keywords: ["AZURE_OPENAI"] },
  { name: "Hugging Face", category: "ai", keywords: ["HUGGINGFACE", "HF_API_TOKEN"] },
  { name: "Replicate", category: "ai", keywords: ["REPLICATE"] },
  { name: "Stability AI", category: "ai", keywords: ["STABILITY_AI", "STABILITY_API"] },
  { name: "ElevenLabs", category: "ai", keywords: ["ELEVENLABS"] },
  { name: "AssemblyAI", category: "ai", keywords: ["ASSEMBLYAI"] },
  { name: "Deepgram", category: "ai", keywords: ["DEEPGRAM"] },
  { name: "Pinecone", category: "ai", keywords: ["PINECONE"] },
  { name: "Weaviate", category: "ai", keywords: ["WEAVIATE"] },
  { name: "Qdrant", category: "ai", keywords: ["QDRANT"] },
  { name: "Chroma", category: "ai", keywords: ["CHROMA_"] },
  { name: "Milvus", category: "ai", keywords: ["MILVUS"] },
  { name: "LangChain", category: "ai", keywords: ["LANGCHAIN"] },
  { name: "LangSmith", category: "ai", keywords: ["LANGSMITH"] },
  { name: "Together AI", category: "ai", keywords: ["TOGETHER_AI", "TOGETHERAI"] },
  { name: "Mistral AI", category: "ai", keywords: ["MISTRAL"] },
  { name: "Perplexity", category: "ai", keywords: ["PERPLEXITY"] },
  { name: "Groq", category: "ai", keywords: ["GROQ_API"] },
  { name: "Fireworks AI", category: "ai", keywords: ["FIREWORKS_AI"] },
  { name: "DeepL", category: "ai", keywords: ["DEEPL_API"] },
  { name: "RunPod", category: "ai", keywords: ["RUNPOD"] },
  { name: "Modal", category: "ai", keywords: ["MODAL_TOKEN"] },
  { name: "Baseten", category: "ai", keywords: ["BASETEN"] },
  { name: "NVIDIA NIM", category: "ai", keywords: ["NVIDIA_API"] },
  { name: "AI21 Labs", category: "ai", keywords: ["AI21_API"] },

  // ---- Payments (≈40) ----
  { name: "Stripe", category: "payments", keywords: ["STRIPE"] },
  { name: "PayPal", category: "payments", keywords: ["PAYPAL"] },
  { name: "Square", category: "payments", keywords: ["SQUARE_ACCESS", "SQUARE_APPLICATION"] },
  { name: "Braintree", category: "payments", keywords: ["BRAINTREE"] },
  { name: "Adyen", category: "payments", keywords: ["ADYEN"] },
  { name: "Razorpay", category: "payments", keywords: ["RAZORPAY"] },
  { name: "Paddle", category: "payments", keywords: ["PADDLE"] },
  { name: "Lemon Squeezy", category: "payments", keywords: ["LEMONSQUEEZY", "LEMON_SQUEEZY"] },
  { name: "Chargebee", category: "payments", keywords: ["CHARGEBEE"] },
  { name: "Recurly", category: "payments", keywords: ["RECURLY"] },
  { name: "WooCommerce", category: "payments", keywords: ["WOOCOMMERCE"] },
  { name: "Shopify", category: "payments", keywords: ["SHOPIFY"] },
  { name: "BigCommerce", category: "payments", keywords: ["BIGCOMMERCE"] },
  { name: "Klarna", category: "payments", keywords: ["KLARNA"] },
  { name: "Afterpay", category: "payments", keywords: ["AFTERPAY"] },
  { name: "Affirm", category: "payments", keywords: ["AFFIRM_"] },
  { name: "Coinbase Commerce", category: "payments", keywords: ["COINBASE_COMMERCE"] },
  { name: "Wise", category: "payments", keywords: ["WISE_API"] },
  { name: "Plaid", category: "payments", keywords: ["PLAID"] },
  { name: "Dwolla", category: "payments", keywords: ["DWOLLA"] },
  { name: "GoCardless", category: "payments", keywords: ["GOCARDLESS"] },
  { name: "Mollie", category: "payments", keywords: ["MOLLIE"] },
  { name: "Checkout.com", category: "payments", keywords: ["CHECKOUT_COM", "CKO_SECRET"] },
  { name: "Worldpay", category: "payments", keywords: ["WORLDPAY"] },
  { name: "Authorize.Net", category: "payments", keywords: ["AUTHORIZE_NET", "AUTHNET"] },
  { name: "2Checkout / Verifone", category: "payments", keywords: ["2CHECKOUT", "VERIFONE"] },
  { name: "Payoneer", category: "payments", keywords: ["PAYONEER"] },
  { name: "Skrill", category: "payments", keywords: ["SKRILL"] },
  { name: "Alipay", category: "payments", keywords: ["ALIPAY"] },
  { name: "WeChat Pay", category: "payments", keywords: ["WECHAT_PAY"] },
  { name: "Revolut Business", category: "payments", keywords: ["REVOLUT_"] },
  { name: "Currencycloud", category: "payments", keywords: ["CURRENCYCLOUD"] },
  { name: "Marqeta", category: "payments", keywords: ["MARQETA"] },
  { name: "Xendit", category: "payments", keywords: ["XENDIT"] },
  { name: "Flutterwave", category: "payments", keywords: ["FLUTTERWAVE"] },
  { name: "Paystack", category: "payments", keywords: ["PAYSTACK"] },
  { name: "Cashfree", category: "payments", keywords: ["CASHFREE"] },
  { name: "Instamojo", category: "payments", keywords: ["INSTAMOJO"] },
  { name: "PayU", category: "payments", keywords: ["PAYU_"] },
  { name: "Payrexx", category: "payments", keywords: ["PAYREXX"] },

  // ---- Analytics / product (≈25) ----
  { name: "Google Analytics", category: "analytics", keywords: ["GOOGLE_ANALYTICS", "GA_MEASUREMENT_ID", "GA_TRACKING_ID"] },
  { name: "Mixpanel", category: "analytics", keywords: ["MIXPANEL"] },
  { name: "Amplitude", category: "analytics", keywords: ["AMPLITUDE"] },
  { name: "Segment", category: "analytics", keywords: ["SEGMENT_WRITE_KEY", "SEGMENT_API_KEY"] },
  { name: "PostHog", category: "analytics", keywords: ["POSTHOG"] },
  { name: "Heap", category: "analytics", keywords: ["HEAP_APP_ID"] },
  { name: "Hotjar", category: "analytics", keywords: ["HOTJAR"] },
  { name: "FullStory", category: "analytics", keywords: ["FULLSTORY"] },
  { name: "Plausible", category: "analytics", keywords: ["PLAUSIBLE"] },
  { name: "Fathom Analytics", category: "analytics", keywords: ["FATHOM_SITE_ID", "FATHOM_ANALYTICS"] },
  { name: "Matomo", category: "analytics", keywords: ["MATOMO"] },
  { name: "Pendo", category: "analytics", keywords: ["PENDO_"] },
  { name: "Countly", category: "analytics", keywords: ["COUNTLY"] },
  { name: "Kissmetrics", category: "analytics", keywords: ["KISSMETRICS"] },
  { name: "Woopra", category: "analytics", keywords: ["WOOPRA"] },
  { name: "Chartbeat", category: "analytics", keywords: ["CHARTBEAT"] },
  { name: "Snowplow", category: "analytics", keywords: ["SNOWPLOW"] },
  { name: "June.so", category: "analytics", keywords: ["JUNE_API_KEY"] },
  { name: "RudderStack", category: "analytics", keywords: ["RUDDERSTACK"] },
  { name: "Statsig", category: "analytics", keywords: ["STATSIG"] },
  { name: "VWO", category: "analytics", keywords: ["VWO_ACCOUNT"] },
  { name: "Optimizely", category: "analytics", keywords: ["OPTIMIZELY"] },
  { name: "Split.io", category: "analytics", keywords: ["SPLIT_IO", "SPLITIO"] },
  { name: "Piwik PRO", category: "analytics", keywords: ["PIWIKPRO"] },
  { name: "Smartlook", category: "analytics", keywords: ["SMARTLOOK"] },

  // ---- Monitoring / observability (≈30) ----
  { name: "Sentry", category: "monitoring", keywords: ["SENTRY"] },
  { name: "Datadog", category: "monitoring", keywords: ["DATADOG", "DD_API_KEY"] },
  { name: "New Relic", category: "monitoring", keywords: ["NEW_RELIC", "NEWRELIC"] },
  { name: "LogRocket", category: "monitoring", keywords: ["LOGROCKET"] },
  { name: "Bugsnag", category: "monitoring", keywords: ["BUGSNAG"] },
  { name: "Rollbar", category: "monitoring", keywords: ["ROLLBAR"] },
  { name: "Honeybadger", category: "monitoring", keywords: ["HONEYBADGER"] },
  { name: "PagerDuty", category: "monitoring", keywords: ["PAGERDUTY"] },
  { name: "Opsgenie", category: "monitoring", keywords: ["OPSGENIE"] },
  { name: "Grafana", category: "monitoring", keywords: ["GRAFANA"] },
  { name: "Prometheus", category: "monitoring", keywords: ["PROMETHEUS"] },
  { name: "Splunk", category: "monitoring", keywords: ["SPLUNK"] },
  { name: "Loggly", category: "monitoring", keywords: ["LOGGLY"] },
  { name: "Papertrail", category: "monitoring", keywords: ["PAPERTRAIL"] },
  { name: "Logtail", category: "monitoring", keywords: ["LOGTAIL"] },
  { name: "Better Stack", category: "monitoring", keywords: ["BETTERSTACK", "BETTER_STACK"] },
  { name: "Checkly", category: "monitoring", keywords: ["CHECKLY"] },
  { name: "UptimeRobot", category: "monitoring", keywords: ["UPTIMEROBOT"] },
  { name: "Atlassian Statuspage", category: "monitoring", keywords: ["STATUSPAGE_"] },
  { name: "Instabug", category: "monitoring", keywords: ["INSTABUG"] },
  { name: "Raygun", category: "monitoring", keywords: ["RAYGUN"] },
  { name: "AppSignal", category: "monitoring", keywords: ["APPSIGNAL"] },
  { name: "Elastic APM", category: "monitoring", keywords: ["ELASTIC_APM"] },
  { name: "Dynatrace", category: "monitoring", keywords: ["DYNATRACE"] },
  { name: "AppDynamics", category: "monitoring", keywords: ["APPDYNAMICS"] },
  { name: "Coralogix", category: "monitoring", keywords: ["CORALOGIX"] },
  { name: "Highlight.io", category: "monitoring", keywords: ["HIGHLIGHT_IO", "HIGHLIGHT_PROJECT"] },
  { name: "Honeycomb", category: "monitoring", keywords: ["HONEYCOMB"] },
  { name: "Axiom", category: "monitoring", keywords: ["AXIOM_TOKEN", "AXIOM_DATASET"] },
  { name: "Grafana Cloud", category: "monitoring", keywords: ["GRAFANA_CLOUD"] },

  // ---- CI/CD & hosting/deploy (≈25) ----
  { name: "GitHub Actions", category: "ci", keywords: ["GITHUB_TOKEN", "GH_TOKEN"] },
  { name: "CircleCI", category: "ci", keywords: ["CIRCLECI", "CIRCLE_CI"] },
  { name: "Travis CI", category: "ci", keywords: ["TRAVIS_"] },
  { name: "Jenkins", category: "ci", keywords: ["JENKINS_"] },
  { name: "GitLab CI", category: "ci", keywords: ["GITLAB_CI", "CI_JOB_TOKEN"] },
  { name: "Vercel", category: "hosting", keywords: ["VERCEL_TOKEN", "VERCEL_PROJECT"] },
  { name: "Netlify", category: "hosting", keywords: ["NETLIFY_"] },
  { name: "Render", category: "hosting", keywords: ["RENDER_API_KEY"] },
  { name: "Railway", category: "hosting", keywords: ["RAILWAY_TOKEN"] },
  { name: "Fly.io", category: "hosting", keywords: ["FLY_API_TOKEN", "FLY_IO"] },
  { name: "Heroku", category: "hosting", keywords: ["HEROKU_API_KEY"] },
  { name: "DigitalOcean App Platform", category: "hosting", keywords: ["DIGITALOCEAN_TOKEN", "DO_API_TOKEN"] },
  { name: "AWS Amplify", category: "hosting", keywords: ["AMPLIFY_APP_ID"] },
  { name: "Google Cloud Run", category: "hosting", keywords: ["CLOUD_RUN_"] },
  { name: "Azure DevOps", category: "ci", keywords: ["AZURE_DEVOPS"] },
  { name: "Buildkite", category: "ci", keywords: ["BUILDKITE"] },
  { name: "Drone CI", category: "ci", keywords: ["DRONE_TOKEN"] },
  { name: "TeamCity", category: "ci", keywords: ["TEAMCITY"] },
  { name: "Bitrise", category: "ci", keywords: ["BITRISE_"] },
  { name: "Codemagic", category: "ci", keywords: ["CODEMAGIC"] },
  { name: "Semaphore CI", category: "ci", keywords: ["SEMAPHORE_"] },
  { name: "AppVeyor", category: "ci", keywords: ["APPVEYOR"] },
  { name: "Argo CD", category: "ci", keywords: ["ARGOCD"] },
  { name: "Spinnaker", category: "ci", keywords: ["SPINNAKER_"] },
  { name: "Terraform Cloud", category: "ci", keywords: ["TERRAFORM_CLOUD", "TFC_TOKEN"] },

  // ---- CRM / support / no-code (≈20) ----
  { name: "Salesforce", category: "crm", keywords: ["SALESFORCE"] },
  { name: "HubSpot", category: "crm", keywords: ["HUBSPOT"] },
  { name: "Zendesk", category: "crm", keywords: ["ZENDESK"] },
  { name: "Intercom", category: "crm", keywords: ["INTERCOM_"] },
  { name: "Freshdesk", category: "crm", keywords: ["FRESHDESK"] },
  { name: "Zoho CRM", category: "crm", keywords: ["ZOHO_CRM"] },
  { name: "Pipedrive", category: "crm", keywords: ["PIPEDRIVE"] },
  { name: "Close CRM", category: "crm", keywords: ["CLOSECRM", "CLOSE_CRM_API"] },
  { name: "Copper CRM", category: "crm", keywords: ["COPPER_CRM"] },
  { name: "Front", category: "crm", keywords: ["FRONTAPP", "FRONT_API_TOKEN"] },
  { name: "Help Scout", category: "crm", keywords: ["HELPSCOUT"] },
  { name: "Drift", category: "crm", keywords: ["DRIFT_API"] },
  { name: "Groove HQ", category: "crm", keywords: ["GROOVEHQ"] },
  { name: "Kustomer", category: "crm", keywords: ["KUSTOMER"] },
  { name: "Gorgias", category: "crm", keywords: ["GORGIAS"] },
  { name: "Zapier", category: "crm", keywords: ["ZAPIER_WEBHOOK"] },
  { name: "Make (Integromat)", category: "crm", keywords: ["MAKE_WEBHOOK", "INTEGROMAT"] },
  { name: "n8n", category: "crm", keywords: ["N8N_API_KEY", "N8N_WEBHOOK"] },
  { name: "Freshsales", category: "crm", keywords: ["FRESHSALES"] },
  { name: "Insightly", category: "crm", keywords: ["INSIGHTLY"] },

  // ---- Search (≈9) ----
  { name: "Algolia", category: "search", keywords: ["ALGOLIA"] },
  { name: "Elasticsearch", category: "search", keywords: ["ELASTICSEARCH", "ELASTIC_CLOUD"] },
  { name: "Meilisearch", category: "search", keywords: ["MEILISEARCH", "MEILI_"] },
  { name: "Typesense", category: "search", keywords: ["TYPESENSE"] },
  { name: "Apache Solr", category: "search", keywords: ["SOLR_"] },
  { name: "Amazon CloudSearch", category: "search", keywords: ["CLOUDSEARCH"] },
  { name: "Swiftype", category: "search", keywords: ["SWIFTYPE"] },
  { name: "Bonsai", category: "search", keywords: ["BONSAI_URL"] },
  { name: "OpenSearch", category: "search", keywords: ["OPENSEARCH"] },

  // ---- Feature flags (≈7) ----
  { name: "LaunchDarkly", category: "feature-flags", keywords: ["LAUNCHDARKLY"] },
  { name: "Flagsmith", category: "feature-flags", keywords: ["FLAGSMITH"] },
  { name: "Unleash", category: "feature-flags", keywords: ["UNLEASH_"] },
  { name: "ConfigCat", category: "feature-flags", keywords: ["CONFIGCAT"] },
  { name: "GrowthBook", category: "feature-flags", keywords: ["GROWTHBOOK"] },
  { name: "Harness Feature Flags", category: "feature-flags", keywords: ["HARNESS_FF"] },
  { name: "DevCycle", category: "feature-flags", keywords: ["DEVCYCLE"] },

  // ---- Maps / geo (≈9) ----
  { name: "Google Maps", category: "maps", keywords: ["GOOGLE_MAPS"] },
  { name: "Mapbox", category: "maps", keywords: ["MAPBOX"] },
  { name: "HERE Maps", category: "maps", keywords: ["HERE_MAPS", "HERE_API_KEY"] },
  { name: "TomTom", category: "maps", keywords: ["TOMTOM"] },
  { name: "MapTiler", category: "maps", keywords: ["MAPTILER"] },
  { name: "Geocodio", category: "maps", keywords: ["GEOCODIO"] },
  { name: "ipstack", category: "maps", keywords: ["IPSTACK"] },
  { name: "MaxMind", category: "maps", keywords: ["MAXMIND"] },
  { name: "What3words", category: "maps", keywords: ["WHAT3WORDS"] },

  // ---- Video / media (≈12) ----
  { name: "Mux", category: "video", keywords: ["MUX_TOKEN", "MUX_SECRET"] },
  { name: "Cloudflare Stream", category: "video", keywords: ["CLOUDFLARE_STREAM"] },
  { name: "Vimeo", category: "video", keywords: ["VIMEO_"] },
  { name: "Zoom", category: "video", keywords: ["ZOOM_API_KEY", "ZOOM_CLIENT_ID"] },
  { name: "Twilio Video", category: "video", keywords: ["TWILIO_VIDEO"] },
  { name: "Agora", category: "video", keywords: ["AGORA_APP_ID"] },
  { name: "Daily.co", category: "video", keywords: ["DAILY_CO", "DAILY_API_KEY"] },
  { name: "LiveKit", category: "video", keywords: ["LIVEKIT_"] },
  { name: "Wowza", category: "video", keywords: ["WOWZA_"] },
  { name: "JW Player", category: "video", keywords: ["JWPLAYER"] },
  { name: "Bitmovin", category: "video", keywords: ["BITMOVIN"] },
  { name: "Amazon IVS", category: "video", keywords: ["AMAZON_IVS", "AWS_IVS"] },

  // ---- CMS (≈12) ----
  { name: "Contentful", category: "cms", keywords: ["CONTENTFUL"] },
  { name: "Sanity", category: "cms", keywords: ["SANITY_"] },
  { name: "Strapi", category: "cms", keywords: ["STRAPI_"] },
  { name: "Prismic", category: "cms", keywords: ["PRISMIC"] },
  { name: "Storyblok", category: "cms", keywords: ["STORYBLOK"] },
  { name: "Ghost", category: "cms", keywords: ["GHOST_API", "GHOST_CONTENT_KEY"] },
  { name: "Payload CMS", category: "cms", keywords: ["PAYLOAD_SECRET", "PAYLOAD_CMS"] },
  { name: "WordPress", category: "cms", keywords: ["WORDPRESS_API", "WP_API"] },
  { name: "Butter CMS", category: "cms", keywords: ["BUTTERCMS"] },
  { name: "Contentstack", category: "cms", keywords: ["CONTENTSTACK"] },
  { name: "Hygraph (GraphCMS)", category: "cms", keywords: ["HYGRAPH", "GRAPHCMS"] },
  { name: "Builder.io", category: "cms", keywords: ["BUILDER_IO", "BUILDER_API_KEY"] },

  // ---- Security / secrets management (≈12) ----
  { name: "HashiCorp Vault", category: "security", keywords: ["VAULT_TOKEN", "VAULT_ADDR"] },
  { name: "AWS Secrets Manager", category: "security", keywords: ["SECRETS_MANAGER"] },
  { name: "1Password", category: "security", keywords: ["OP_SERVICE_ACCOUNT", "ONEPASSWORD"] },
  { name: "Doppler", category: "security", keywords: ["DOPPLER_TOKEN"] },
  { name: "Infisical", category: "security", keywords: ["INFISICAL"] },
  { name: "EnvKey", category: "security", keywords: ["ENVKEY"] },
  { name: "Akeyless", category: "security", keywords: ["AKEYLESS"] },
  { name: "CyberArk", category: "security", keywords: ["CYBERARK"] },
  { name: "Cloudflare Turnstile", category: "security", keywords: ["TURNSTILE_SECRET", "TURNSTILE_SITE_KEY"] },
  { name: "hCaptcha", category: "security", keywords: ["HCAPTCHA"] },
  { name: "Google reCAPTCHA", category: "security", keywords: ["RECAPTCHA"] },
  { name: "Snyk", category: "security", keywords: ["SNYK_TOKEN"] },

  // ---- Blockchain / web3 (≈12) ----
  { name: "Alchemy", category: "blockchain", keywords: ["ALCHEMY_API", "ALCHEMY_KEY"] },
  { name: "Infura", category: "blockchain", keywords: ["INFURA"] },
  { name: "Moralis", category: "blockchain", keywords: ["MORALIS"] },
  { name: "QuickNode", category: "blockchain", keywords: ["QUICKNODE"] },
  { name: "Etherscan", category: "blockchain", keywords: ["ETHERSCAN_API"] },
  { name: "Coinbase", category: "blockchain", keywords: ["COINBASE_API"] },
  { name: "WalletConnect", category: "blockchain", keywords: ["WALLETCONNECT"] },
  { name: "The Graph", category: "blockchain", keywords: ["THEGRAPH", "GRAPH_API_KEY"] },
  { name: "Chainlink", category: "blockchain", keywords: ["CHAINLINK_"] },
  { name: "OpenSea", category: "blockchain", keywords: ["OPENSEA_API"] },
  { name: "Thirdweb", category: "blockchain", keywords: ["THIRDWEB"] },
  { name: "Pinata (IPFS)", category: "blockchain", keywords: ["PINATA_"] },

  // ---- Social platform APIs (≈10) ----
  { name: "Twitter/X API", category: "social", keywords: ["TWITTER_API", "TWITTER_BEARER", "X_API_KEY"] },
  { name: "Facebook Graph API", category: "social", keywords: ["FACEBOOK_GRAPH", "FB_APP_SECRET"] },
  { name: "Instagram API", category: "social", keywords: ["INSTAGRAM_API"] },
  { name: "LinkedIn API", category: "social", keywords: ["LINKEDIN_API"] },
  { name: "TikTok API", category: "social", keywords: ["TIKTOK_API"] },
  { name: "Reddit API", category: "social", keywords: ["REDDIT_CLIENT_ID"] },
  { name: "YouTube Data API", category: "social", keywords: ["YOUTUBE_API"] },
  { name: "Pinterest API", category: "social", keywords: ["PINTEREST_API"] },
  { name: "Snapchat API", category: "social", keywords: ["SNAPCHAT_API"] },
  { name: "Discord Bot API", category: "social", keywords: ["DISCORD_BOT_TOKEN"] },

  // ---- General cloud hosting (≈9, generic infra providers) ----
  { name: "Cloudflare", category: "hosting", keywords: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ZONE"] },
  { name: "Linode / Akamai Cloud", category: "hosting", keywords: ["LINODE_TOKEN"] },
  { name: "Vultr", category: "hosting", keywords: ["VULTR_API_KEY"] },
  { name: "AWS", category: "hosting", keywords: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"] },
  { name: "Google Cloud Platform", category: "hosting", keywords: ["GOOGLE_APPLICATION_CREDENTIALS", "GCP_PROJECT"] },
  { name: "Microsoft Azure", category: "hosting", keywords: ["AZURE_SUBSCRIPTION", "AZURE_TENANT_ID"] },
  { name: "IBM Cloud", category: "hosting", keywords: ["IBM_CLOUD_API_KEY"] },
  { name: "OVHcloud", category: "hosting", keywords: ["OVH_APPLICATION_KEY"] },
  { name: "Scaleway", category: "hosting", keywords: ["SCALEWAY_"] },

  // ---- Productivity / docs / no-code / misc SaaS (≈60) ----
  { name: "Notion", category: "cms", keywords: ["NOTION_API_KEY", "NOTION_TOKEN"] },
  { name: "Calendly", category: "other", keywords: ["CALENDLY_"] },
  { name: "Typeform", category: "other", keywords: ["TYPEFORM_"] },
  { name: "DocuSign", category: "other", keywords: ["DOCUSIGN_"] },
  { name: "Box", category: "storage", keywords: ["BOX_CLIENT_ID", "BOX_CLIENT_SECRET"] },
  { name: "Dropbox", category: "storage", keywords: ["DROPBOX_"] },
  { name: "Google Workspace", category: "other", keywords: ["GOOGLE_WORKSPACE"] },
  { name: "Microsoft 365", category: "other", keywords: ["MICROSOFT_365", "M365_"] },
  { name: "Loom", category: "video", keywords: ["LOOM_API"] },
  { name: "Miro", category: "other", keywords: ["MIRO_API", "MIRO_TOKEN"] },
  { name: "Figma", category: "other", keywords: ["FIGMA_TOKEN", "FIGMA_API"] },
  { name: "Asana", category: "other", keywords: ["ASANA_"] },
  { name: "Trello", category: "other", keywords: ["TRELLO_"] },
  { name: "Monday.com", category: "other", keywords: ["MONDAY_API"] },
  { name: "ClickUp", category: "other", keywords: ["CLICKUP_"] },
  { name: "Jira", category: "other", keywords: ["JIRA_API", "JIRA_TOKEN"] },
  { name: "Confluence", category: "other", keywords: ["CONFLUENCE_"] },
  { name: "Linear", category: "other", keywords: ["LINEAR_API_KEY"] },
  { name: "Basecamp", category: "other", keywords: ["BASECAMP_"] },
  { name: "Bitbucket", category: "ci", keywords: ["BITBUCKET_"] },
  { name: "npm registry", category: "ci", keywords: ["NPM_TOKEN"] },
  { name: "PyPI", category: "ci", keywords: ["PYPI_TOKEN", "PYPI_API"] },
  { name: "Docker Hub", category: "ci", keywords: ["DOCKERHUB_", "DOCKER_HUB"] },
  { name: "JFrog Artifactory", category: "ci", keywords: ["ARTIFACTORY_"] },
  { name: "Sonatype Nexus", category: "ci", keywords: ["NEXUS_REPOSITORY"] },
  { name: "Sourcegraph", category: "other", keywords: ["SOURCEGRAPH_"] },
  { name: "Postman", category: "other", keywords: ["POSTMAN_API_KEY"] },
  { name: "RapidAPI", category: "other", keywords: ["RAPIDAPI_"] },
  { name: "Insomnia", category: "other", keywords: ["INSOMNIA_API"] },
  { name: "Retool", category: "other", keywords: ["RETOOL_API"] },
  { name: "Appsmith", category: "other", keywords: ["APPSMITH_"] },
  { name: "Bubble", category: "other", keywords: ["BUBBLE_API_TOKEN"] },
  { name: "Webflow", category: "cms", keywords: ["WEBFLOW_"] },
  { name: "Framer", category: "other", keywords: ["FRAMER_TOKEN"] },
  { name: "Squarespace", category: "other", keywords: ["SQUARESPACE_"] },
  { name: "Wix", category: "other", keywords: ["WIX_API_KEY"] },
  { name: "Google Calendar API", category: "other", keywords: ["GOOGLE_CALENDAR_"] },
  { name: "Google Drive API", category: "storage", keywords: ["GOOGLE_DRIVE_"] },
  { name: "Microsoft Graph API", category: "other", keywords: ["MICROSOFT_GRAPH", "MS_GRAPH_"] },
  { name: "Dropbox Sign (HelloSign)", category: "other", keywords: ["HELLOSIGN_", "DROPBOX_SIGN"] },
  { name: "PandaDoc", category: "other", keywords: ["PANDADOC_"] },
  { name: "Adobe Sign", category: "other", keywords: ["ADOBE_SIGN"] },
  { name: "Smartsheet", category: "other", keywords: ["SMARTSHEET_"] },
  { name: "Coda", category: "other", keywords: ["CODA_API"] },
  { name: "Freshservice", category: "crm", keywords: ["FRESHSERVICE_"] },
  { name: "ServiceNow", category: "crm", keywords: ["SERVICENOW_"] },
  { name: "Jira Service Management", category: "crm", keywords: ["JSM_API"] },
  { name: "Splunk On-Call (VictorOps)", category: "monitoring", keywords: ["VICTOROPS_"] },
  { name: "Sumo Logic", category: "monitoring", keywords: ["SUMOLOGIC", "SUMO_LOGIC"] },
  { name: "Graylog", category: "monitoring", keywords: ["GRAYLOG_"] },
  { name: "Mezmo (LogDNA)", category: "monitoring", keywords: ["LOGDNA_", "MEZMO_"] },
  { name: "Cronitor", category: "monitoring", keywords: ["CRONITOR_"] },
  { name: "Healthchecks.io", category: "monitoring", keywords: ["HEALTHCHECKS_IO"] },
  { name: "StatusCake", category: "monitoring", keywords: ["STATUSCAKE_"] },
  { name: "Pingdom", category: "monitoring", keywords: ["PINGDOM_"] },
  { name: "Site24x7", category: "monitoring", keywords: ["SITE24X7_"] },
  { name: "Freshping", category: "monitoring", keywords: ["FRESHPING_"] },
  { name: "ManageEngine", category: "monitoring", keywords: ["MANAGEENGINE_"] },
  { name: "Zoho Books", category: "other", keywords: ["ZOHO_BOOKS"] },
  { name: "QuickBooks", category: "other", keywords: ["QUICKBOOKS_"] },
  { name: "Xero", category: "other", keywords: ["XERO_CLIENT"] },
  { name: "FreshBooks", category: "other", keywords: ["FRESHBOOKS_"] },
];

/**
 * All env-var name variants recognized across the provider database,
 * generated by combining each provider's primary keyword with the
 * canonical suffixes for its category (e.g. Stripe + payments suffixes ->
 * STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, ...). Computed once at module
 * load and used for coverage stats and the docs "supported providers" page
 * — not for classification itself (see `findProvider`, which matches by
 * substring so it also catches variants not in this exact list).
 */
export const KNOWN_ENV_KEYS: string[] = (() => {
  const keys = new Set<string>();
  for (const provider of PROVIDERS) {
    const suffixes = CATEGORY_SUFFIXES[provider.category];
    const primary = provider.keywords[0].replace(/_$/, "");
    for (const suffix of suffixes) {
      keys.add(`${primary}_${suffix}`);
    }
  }
  return Array.from(keys).sort();
})();

/**
 * Finds the most specific provider whose keyword appears in the given env
 * var name. Prefers the longest matching keyword so that, e.g., a var
 * containing both "AWS_" and "AWS_S3" style tokens resolves to the more
 * specific vendor rather than the generic one.
 */
export function findProvider(key: string): Provider | undefined {
  const upper = key.toUpperCase();
  let best: Provider | undefined;
  let bestLength = 0;
  for (const provider of PROVIDERS) {
    for (const keyword of provider.keywords) {
      if (keyword.length > bestLength && upper.includes(keyword)) {
        best = provider;
        bestLength = keyword.length;
      }
    }
  }
  return best;
}

export const PROVIDER_COUNT = PROVIDERS.length;
